--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PrestadorServicoDB DROP FOREIGN KEY FuncionarioContrata;

ALTER TABLE PrestaDB DROP FOREIGN KEY ServicoPrestado;

ALTER TABLE PrestaDB DROP FOREIGN KEY PrestadorPresta;

ALTER TABLE VendaDB DROP FOREIGN KEY FuncionarioVende;

ALTER TABLE VendaDB DROP FOREIGN KEY ClienteVende;

ALTER TABLE VendaDB DROP FOREIGN KEY VendeCarro;

ALTER TABLE CompraDB DROP FOREIGN KEY CompraCarro;

ALTER TABLE CompraDB DROP FOREIGN KEY ClienteCompra;

ALTER TABLE CompraDB DROP FOREIGN KEY FuncionarioCompra;

ALTER TABLE RecebeDB DROP FOREIGN KEY RecebePrestadorServico;

ALTER TABLE RecebeDB DROP FOREIGN KEY RecebeServico;

ALTER TABLE RecebeDB DROP FOREIGN KEY CarroRecebe;

ALTER TABLE ClienteDB DROP PRIMARY KEY;

ALTER TABLE FuncionarioDB DROP PRIMARY KEY;

ALTER TABLE CarroDB DROP PRIMARY KEY;

ALTER TABLE PrestadorServicoDB DROP PRIMARY KEY;

ALTER TABLE ServicoDB DROP PRIMARY KEY;

ALTER TABLE PrestaDB DROP PRIMARY KEY;

ALTER TABLE VendaDB DROP PRIMARY KEY;

ALTER TABLE CompraDB DROP PRIMARY KEY;

ALTER TABLE RecebeDB DROP PRIMARY KEY;

DROP TABLE ClienteDB;

DROP TABLE FuncionarioDB;

DROP TABLE CarroDB;

DROP TABLE PrestadorServicoDB;

DROP TABLE ServicoDB;

DROP TABLE PrestaDB;

DROP TABLE VendaDB;

DROP TABLE CompraDB;

DROP TABLE RecebeDB;

